<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class SeatSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $date = date('Y-m-d H:i:s');
        $seats = [
            ['row_name' => 'A', 'column_no' => 1, 'status' => 0, 'created_at' => $date, 'updated_at' => $date],
            ['row_name' => 'A', 'column_no' => 2, 'status' => 0, 'created_at' => $date, 'updated_at' => $date],
            ['row_name' => 'A', 'column_no' => 3, 'status' => 0, 'created_at' => $date, 'updated_at' => $date],
            ['row_name' => 'A', 'column_no' => 4, 'status' => 0, 'created_at' => $date, 'updated_at' => $date],
            ['row_name' => 'A', 'column_no' => 5, 'status' => 0, 'created_at' => $date, 'updated_at' => $date],
            ['row_name' => 'A', 'column_no' => 6, 'status' => 0, 'created_at' => $date, 'updated_at' => $date],
            ['row_name' => 'A', 'column_no' => 7, 'status' => 0, 'created_at' => $date, 'updated_at' => $date],
            ['row_name' => 'A', 'column_no' => 8, 'status' => 0, 'created_at' => $date, 'updated_at' => $date],
            ['row_name' => 'A', 'column_no' => 9, 'status' => 0, 'created_at' => $date, 'updated_at' => $date],
            ['row_name' => 'A', 'column_no' => 10, 'status' => 0, 'created_at' => $date, 'updated_at' => $date],
            ['row_name' => 'B', 'column_no' => 1, 'status' => 0, 'created_at' => $date, 'updated_at' => $date],
            ['row_name' => 'B', 'column_no' => 2, 'status' => 0, 'created_at' => $date, 'updated_at' => $date],
            ['row_name' => 'B', 'column_no' => 3, 'status' => 0, 'created_at' => $date, 'updated_at' => $date],
            ['row_name' => 'B', 'column_no' => 4, 'status' => 0, 'created_at' => $date, 'updated_at' => $date],
            ['row_name' => 'B', 'column_no' => 5, 'status' => 0, 'created_at' => $date, 'updated_at' => $date],
            ['row_name' => 'B', 'column_no' => 6, 'status' => 0, 'created_at' => $date, 'updated_at' => $date],
            ['row_name' => 'B', 'column_no' => 7, 'status' => 0, 'created_at' => $date, 'updated_at' => $date],
            ['row_name' => 'B', 'column_no' => 8, 'status' => 0, 'created_at' => $date, 'updated_at' => $date],
            ['row_name' => 'B', 'column_no' => 9, 'status' => 0, 'created_at' => $date, 'updated_at' => $date],
            ['row_name' => 'B', 'column_no' => 10, 'status' => 0, 'created_at' => $date, 'updated_at' => $date],
            ['row_name' => 'C', 'column_no' => 1, 'status' => 0, 'created_at' => $date, 'updated_at' => $date],
            ['row_name' => 'C', 'column_no' => 2, 'status' => 0, 'created_at' => $date, 'updated_at' => $date],
            ['row_name' => 'C', 'column_no' => 3, 'status' => 0, 'created_at' => $date, 'updated_at' => $date],
            ['row_name' => 'C', 'column_no' => 4, 'status' => 0, 'created_at' => $date, 'updated_at' => $date],
            ['row_name' => 'C', 'column_no' => 5, 'status' => 0, 'created_at' => $date, 'updated_at' => $date],
            ['row_name' => 'C', 'column_no' => 6, 'status' => 0, 'created_at' => $date, 'updated_at' => $date],
            ['row_name' => 'C', 'column_no' => 7, 'status' => 0, 'created_at' => $date, 'updated_at' => $date],
            ['row_name' => 'C', 'column_no' => 8, 'status' => 0, 'created_at' => $date, 'updated_at' => $date],
            ['row_name' => 'C', 'column_no' => 9, 'status' => 0, 'created_at' => $date, 'updated_at' => $date],
            ['row_name' => 'C', 'column_no' => 10, 'status' => 0, 'created_at' => $date, 'updated_at' => $date],
            ['row_name' => 'D', 'column_no' => 1, 'status' => 0, 'created_at' => $date, 'updated_at' => $date],
            ['row_name' => 'D', 'column_no' => 2, 'status' => 0, 'created_at' => $date, 'updated_at' => $date],
            ['row_name' => 'D', 'column_no' => 3, 'status' => 0, 'created_at' => $date, 'updated_at' => $date],
            ['row_name' => 'D', 'column_no' => 4, 'status' => 0, 'created_at' => $date, 'updated_at' => $date],
            ['row_name' => 'D', 'column_no' => 5, 'status' => 0, 'created_at' => $date, 'updated_at' => $date],
            ['row_name' => 'D', 'column_no' => 6, 'status' => 0, 'created_at' => $date, 'updated_at' => $date],
            ['row_name' => 'D', 'column_no' => 7, 'status' => 0, 'created_at' => $date, 'updated_at' => $date],
            ['row_name' => 'D', 'column_no' => 8, 'status' => 0, 'created_at' => $date, 'updated_at' => $date],
            ['row_name' => 'D', 'column_no' => 9, 'status' => 0, 'created_at' => $date, 'updated_at' => $date],
            ['row_name' => 'D', 'column_no' => 10, 'status' => 0, 'created_at' => $date, 'updated_at' => $date],
            ['row_name' => 'E', 'column_no' => 1, 'status' => 0, 'created_at' => $date, 'updated_at' => $date],
            ['row_name' => 'E', 'column_no' => 2, 'status' => 0, 'created_at' => $date, 'updated_at' => $date],
            ['row_name' => 'E', 'column_no' => 3, 'status' => 0, 'created_at' => $date, 'updated_at' => $date],
            ['row_name' => 'E', 'column_no' => 4, 'status' => 0, 'created_at' => $date, 'updated_at' => $date],
            ['row_name' => 'E', 'column_no' => 5, 'status' => 0, 'created_at' => $date, 'updated_at' => $date],
            ['row_name' => 'E', 'column_no' => 6, 'status' => 0, 'created_at' => $date, 'updated_at' => $date],
            ['row_name' => 'E', 'column_no' => 7, 'status' => 0, 'created_at' => $date, 'updated_at' => $date],
            ['row_name' => 'E', 'column_no' => 8, 'status' => 0, 'created_at' => $date, 'updated_at' => $date],
            ['row_name' => 'E', 'column_no' => 9, 'status' => 0, 'created_at' => $date, 'updated_at' => $date],
            ['row_name' => 'E', 'column_no' => 10, 'status' => 0, 'created_at' => $date, 'updated_at' => $date],
            ['row_name' => 'F', 'column_no' => 1, 'status' => 0, 'created_at' => $date, 'updated_at' => $date],
            ['row_name' => 'F', 'column_no' => 2, 'status' => 0, 'created_at' => $date, 'updated_at' => $date],
            ['row_name' => 'F', 'column_no' => 3, 'status' => 0, 'created_at' => $date, 'updated_at' => $date],
            ['row_name' => 'F', 'column_no' => 4, 'status' => 0, 'created_at' => $date, 'updated_at' => $date],
            ['row_name' => 'F', 'column_no' => 5, 'status' => 0, 'created_at' => $date, 'updated_at' => $date],
            ['row_name' => 'F', 'column_no' => 6, 'status' => 0, 'created_at' => $date, 'updated_at' => $date],
            ['row_name' => 'F', 'column_no' => 7, 'status' => 0, 'created_at' => $date, 'updated_at' => $date],
            ['row_name' => 'F', 'column_no' => 8, 'status' => 0, 'created_at' => $date, 'updated_at' => $date],
            ['row_name' => 'F', 'column_no' => 9, 'status' => 0, 'created_at' => $date, 'updated_at' => $date],
            ['row_name' => 'F', 'column_no' => 10, 'status' => 0, 'created_at' => $date, 'updated_at' => $date],
            ['row_name' => 'G', 'column_no' => 1, 'status' => 0, 'created_at' => $date, 'updated_at' => $date],
            ['row_name' => 'G', 'column_no' => 2, 'status' => 0, 'created_at' => $date, 'updated_at' => $date],
            ['row_name' => 'G', 'column_no' => 3, 'status' => 0, 'created_at' => $date, 'updated_at' => $date],
            ['row_name' => 'G', 'column_no' => 4, 'status' => 0, 'created_at' => $date, 'updated_at' => $date],
            ['row_name' => 'G', 'column_no' => 5, 'status' => 0, 'created_at' => $date, 'updated_at' => $date],
            ['row_name' => 'G', 'column_no' => 6, 'status' => 0, 'created_at' => $date, 'updated_at' => $date],
            ['row_name' => 'G', 'column_no' => 7, 'status' => 0, 'created_at' => $date, 'updated_at' => $date],
            ['row_name' => 'G', 'column_no' => 8, 'status' => 0, 'created_at' => $date, 'updated_at' => $date],
            ['row_name' => 'G', 'column_no' => 9, 'status' => 0, 'created_at' => $date, 'updated_at' => $date],
            ['row_name' => 'G', 'column_no' => 10, 'status' => 0, 'created_at' => $date, 'updated_at' => $date],
            ['row_name' => 'H', 'column_no' => 1, 'status' => 0, 'created_at' => $date, 'updated_at' => $date],
            ['row_name' => 'H', 'column_no' => 2, 'status' => 0, 'created_at' => $date, 'updated_at' => $date],
            ['row_name' => 'H', 'column_no' => 3, 'status' => 0, 'created_at' => $date, 'updated_at' => $date],
            ['row_name' => 'H', 'column_no' => 4, 'status' => 0, 'created_at' => $date, 'updated_at' => $date],
            ['row_name' => 'H', 'column_no' => 5, 'status' => 0, 'created_at' => $date, 'updated_at' => $date],
            ['row_name' => 'H', 'column_no' => 6, 'status' => 0, 'created_at' => $date, 'updated_at' => $date],
            ['row_name' => 'H', 'column_no' => 7, 'status' => 0, 'created_at' => $date, 'updated_at' => $date],
            ['row_name' => 'H', 'column_no' => 8, 'status' => 0, 'created_at' => $date, 'updated_at' => $date],
            ['row_name' => 'H', 'column_no' => 9, 'status' => 0, 'created_at' => $date, 'updated_at' => $date],
            ['row_name' => 'H', 'column_no' => 10, 'status' => 0, 'created_at' => $date, 'updated_at' => $date],
            ['row_name' => 'I', 'column_no' => 1, 'status' => 0, 'created_at' => $date, 'updated_at' => $date],
            ['row_name' => 'I', 'column_no' => 2, 'status' => 0, 'created_at' => $date, 'updated_at' => $date],
            ['row_name' => 'I', 'column_no' => 3, 'status' => 0, 'created_at' => $date, 'updated_at' => $date],
            ['row_name' => 'I', 'column_no' => 4, 'status' => 0, 'created_at' => $date, 'updated_at' => $date],
            ['row_name' => 'I', 'column_no' => 5, 'status' => 0, 'created_at' => $date, 'updated_at' => $date],
            ['row_name' => 'I', 'column_no' => 6, 'status' => 0, 'created_at' => $date, 'updated_at' => $date],
            ['row_name' => 'I', 'column_no' => 7, 'status' => 0, 'created_at' => $date, 'updated_at' => $date],
            ['row_name' => 'I', 'column_no' => 8, 'status' => 0, 'created_at' => $date, 'updated_at' => $date],
            ['row_name' => 'I', 'column_no' => 9, 'status' => 0, 'created_at' => $date, 'updated_at' => $date],
            ['row_name' => 'I', 'column_no' => 10, 'status' => 0, 'created_at' => $date, 'updated_at' => $date],
            ['row_name' => 'J', 'column_no' => 1, 'status' => 0, 'created_at' => $date, 'updated_at' => $date],
            ['row_name' => 'J', 'column_no' => 2, 'status' => 0, 'created_at' => $date, 'updated_at' => $date],
            ['row_name' => 'J', 'column_no' => 3, 'status' => 0, 'created_at' => $date, 'updated_at' => $date],
            ['row_name' => 'J', 'column_no' => 4, 'status' => 0, 'created_at' => $date, 'updated_at' => $date],
            ['row_name' => 'J', 'column_no' => 5, 'status' => 0, 'created_at' => $date, 'updated_at' => $date],
            ['row_name' => 'J', 'column_no' => 6, 'status' => 0, 'created_at' => $date, 'updated_at' => $date],
            ['row_name' => 'J', 'column_no' => 7, 'status' => 0, 'created_at' => $date, 'updated_at' => $date],
            ['row_name' => 'J', 'column_no' => 8, 'status' => 0, 'created_at' => $date, 'updated_at' => $date],
            ['row_name' => 'J', 'column_no' => 9, 'status' => 0, 'created_at' => $date, 'updated_at' => $date],
            ['row_name' => 'J', 'column_no' => 10, 'status' => 0, 'created_at' => $date, 'updated_at' => $date],
            ['row_name' => 'K', 'column_no' => 1, 'status' => 0, 'created_at' => $date, 'updated_at' => $date],
            ['row_name' => 'K', 'column_no' => 2, 'status' => 0, 'created_at' => $date, 'updated_at' => $date],
            ['row_name' => 'K', 'column_no' => 3, 'status' => 0, 'created_at' => $date, 'updated_at' => $date],
            ['row_name' => 'K', 'column_no' => 4, 'status' => 0, 'created_at' => $date, 'updated_at' => $date],
            ['row_name' => 'K', 'column_no' => 5, 'status' => 0, 'created_at' => $date, 'updated_at' => $date],
            ['row_name' => 'K', 'column_no' => 6, 'status' => 0, 'created_at' => $date, 'updated_at' => $date],
            ['row_name' => 'K', 'column_no' => 7, 'status' => 0, 'created_at' => $date, 'updated_at' => $date],
            ['row_name' => 'K', 'column_no' => 8, 'status' => 0, 'created_at' => $date, 'updated_at' => $date],
            ['row_name' => 'K', 'column_no' => 9, 'status' => 0, 'created_at' => $date, 'updated_at' => $date],
            ['row_name' => 'K', 'column_no' => 10, 'status' => 0, 'created_at' => $date, 'updated_at' => $date],
            ['row_name' => 'L', 'column_no' => 1, 'status' => 0, 'created_at' => $date, 'updated_at' => $date],
            ['row_name' => 'L', 'column_no' => 2, 'status' => 0, 'created_at' => $date, 'updated_at' => $date],
            ['row_name' => 'L', 'column_no' => 3, 'status' => 0, 'created_at' => $date, 'updated_at' => $date],
            ['row_name' => 'L', 'column_no' => 4, 'status' => 0, 'created_at' => $date, 'updated_at' => $date],
            ['row_name' => 'L', 'column_no' => 5, 'status' => 0, 'created_at' => $date, 'updated_at' => $date],
            ['row_name' => 'L', 'column_no' => 6, 'status' => 0, 'created_at' => $date, 'updated_at' => $date],
            ['row_name' => 'L', 'column_no' => 7, 'status' => 0, 'created_at' => $date, 'updated_at' => $date],
            ['row_name' => 'L', 'column_no' => 8, 'status' => 0, 'created_at' => $date, 'updated_at' => $date],
            ['row_name' => 'L', 'column_no' => 9, 'status' => 0, 'created_at' => $date, 'updated_at' => $date],
            ['row_name' => 'L', 'column_no' => 10, 'status' => 0, 'created_at' => $date, 'updated_at' => $date],
            ['row_name' => 'M', 'column_no' => 1, 'status' => 0, 'created_at' => $date, 'updated_at' => $date],
            ['row_name' => 'M', 'column_no' => 2, 'status' => 0, 'created_at' => $date, 'updated_at' => $date],
            ['row_name' => 'M', 'column_no' => 3, 'status' => 0, 'created_at' => $date, 'updated_at' => $date],
            ['row_name' => 'M', 'column_no' => 4, 'status' => 0, 'created_at' => $date, 'updated_at' => $date],
            ['row_name' => 'M', 'column_no' => 5, 'status' => 0, 'created_at' => $date, 'updated_at' => $date],
            ['row_name' => 'M', 'column_no' => 6, 'status' => 0, 'created_at' => $date, 'updated_at' => $date],
            ['row_name' => 'M', 'column_no' => 7, 'status' => 0, 'created_at' => $date, 'updated_at' => $date],
            ['row_name' => 'M', 'column_no' => 8, 'status' => 0, 'created_at' => $date, 'updated_at' => $date],
            ['row_name' => 'M', 'column_no' => 9, 'status' => 0, 'created_at' => $date, 'updated_at' => $date],
            ['row_name' => 'M', 'column_no' => 10, 'status' => 0, 'created_at' => $date, 'updated_at' => $date],
            ['row_name' => 'N', 'column_no' => 1, 'status' => 0, 'created_at' => $date, 'updated_at' => $date],
            ['row_name' => 'N', 'column_no' => 2, 'status' => 0, 'created_at' => $date, 'updated_at' => $date],
            ['row_name' => 'N', 'column_no' => 3, 'status' => 0, 'created_at' => $date, 'updated_at' => $date],
            ['row_name' => 'N', 'column_no' => 4, 'status' => 0, 'created_at' => $date, 'updated_at' => $date],
            ['row_name' => 'N', 'column_no' => 5, 'status' => 0, 'created_at' => $date, 'updated_at' => $date],
            ['row_name' => 'N', 'column_no' => 6, 'status' => 0, 'created_at' => $date, 'updated_at' => $date],
            ['row_name' => 'N', 'column_no' => 7, 'status' => 0, 'created_at' => $date, 'updated_at' => $date],
            ['row_name' => 'N', 'column_no' => 8, 'status' => 0, 'created_at' => $date, 'updated_at' => $date],
            ['row_name' => 'N', 'column_no' => 9, 'status' => 0, 'created_at' => $date, 'updated_at' => $date],
            ['row_name' => 'N', 'column_no' => 10, 'status' => 0, 'created_at' => $date, 'updated_at' => $date],
            ['row_name' => 'O', 'column_no' => 1, 'status' => 0, 'created_at' => $date, 'updated_at' => $date],
            ['row_name' => 'O', 'column_no' => 2, 'status' => 0, 'created_at' => $date, 'updated_at' => $date],
            ['row_name' => 'O', 'column_no' => 3, 'status' => 0, 'created_at' => $date, 'updated_at' => $date],
            ['row_name' => 'O', 'column_no' => 4, 'status' => 0, 'created_at' => $date, 'updated_at' => $date],
            ['row_name' => 'O', 'column_no' => 5, 'status' => 0, 'created_at' => $date, 'updated_at' => $date],
            ['row_name' => 'O', 'column_no' => 6, 'status' => 0, 'created_at' => $date, 'updated_at' => $date],
            ['row_name' => 'O', 'column_no' => 7, 'status' => 0, 'created_at' => $date, 'updated_at' => $date],
            ['row_name' => 'O', 'column_no' => 8, 'status' => 0, 'created_at' => $date, 'updated_at' => $date],
            ['row_name' => 'O', 'column_no' => 9, 'status' => 0, 'created_at' => $date, 'updated_at' => $date],
            ['row_name' => 'O', 'column_no' => 10, 'status' => 0, 'created_at' => $date, 'updated_at' => $date],
            ['row_name' => 'P', 'column_no' => 1, 'status' => 0, 'created_at' => $date, 'updated_at' => $date],
            ['row_name' => 'P', 'column_no' => 2, 'status' => 0, 'created_at' => $date, 'updated_at' => $date],
            ['row_name' => 'P', 'column_no' => 3, 'status' => 0, 'created_at' => $date, 'updated_at' => $date],
            ['row_name' => 'P', 'column_no' => 4, 'status' => 0, 'created_at' => $date, 'updated_at' => $date],
            ['row_name' => 'P', 'column_no' => 5, 'status' => 0, 'created_at' => $date, 'updated_at' => $date],
            ['row_name' => 'P', 'column_no' => 6, 'status' => 0, 'created_at' => $date, 'updated_at' => $date],
            ['row_name' => 'P', 'column_no' => 7, 'status' => 0, 'created_at' => $date, 'updated_at' => $date],
            ['row_name' => 'P', 'column_no' => 8, 'status' => 0, 'created_at' => $date, 'updated_at' => $date],
            ['row_name' => 'P', 'column_no' => 9, 'status' => 0, 'created_at' => $date, 'updated_at' => $date],
            ['row_name' => 'P', 'column_no' => 10, 'status' => 0, 'created_at' => $date, 'updated_at' => $date],
            ['row_name' => 'Q', 'column_no' => 1, 'status' => 0, 'created_at' => $date, 'updated_at' => $date],
            ['row_name' => 'Q', 'column_no' => 2, 'status' => 0, 'created_at' => $date, 'updated_at' => $date],
            ['row_name' => 'Q', 'column_no' => 3, 'status' => 0, 'created_at' => $date, 'updated_at' => $date],
            ['row_name' => 'Q', 'column_no' => 4, 'status' => 0, 'created_at' => $date, 'updated_at' => $date],
            ['row_name' => 'Q', 'column_no' => 5, 'status' => 0, 'created_at' => $date, 'updated_at' => $date],
            ['row_name' => 'Q', 'column_no' => 6, 'status' => 0, 'created_at' => $date, 'updated_at' => $date],
            ['row_name' => 'Q', 'column_no' => 7, 'status' => 0, 'created_at' => $date, 'updated_at' => $date],
            ['row_name' => 'Q', 'column_no' => 8, 'status' => 0, 'created_at' => $date, 'updated_at' => $date],
            ['row_name' => 'Q', 'column_no' => 9, 'status' => 0, 'created_at' => $date, 'updated_at' => $date],
            ['row_name' => 'Q', 'column_no' => 10, 'status' => 0, 'created_at' => $date, 'updated_at' => $date],
            ['row_name' => 'R', 'column_no' => 1, 'status' => 0, 'created_at' => $date, 'updated_at' => $date],
            ['row_name' => 'R', 'column_no' => 2, 'status' => 0, 'created_at' => $date, 'updated_at' => $date],
            ['row_name' => 'R', 'column_no' => 3, 'status' => 0, 'created_at' => $date, 'updated_at' => $date],
            ['row_name' => 'R', 'column_no' => 4, 'status' => 0, 'created_at' => $date, 'updated_at' => $date],
            ['row_name' => 'R', 'column_no' => 5, 'status' => 0, 'created_at' => $date, 'updated_at' => $date],
            ['row_name' => 'R', 'column_no' => 6, 'status' => 0, 'created_at' => $date, 'updated_at' => $date],
            ['row_name' => 'R', 'column_no' => 7, 'status' => 0, 'created_at' => $date, 'updated_at' => $date],
            ['row_name' => 'R', 'column_no' => 8, 'status' => 0, 'created_at' => $date, 'updated_at' => $date],
            ['row_name' => 'R', 'column_no' => 9, 'status' => 0, 'created_at' => $date, 'updated_at' => $date],
            ['row_name' => 'R', 'column_no' => 10, 'status' => 0, 'created_at' => $date, 'updated_at' => $date],
            ['row_name' => 'S', 'column_no' => 1, 'status' => 0, 'created_at' => $date, 'updated_at' => $date],
            ['row_name' => 'S', 'column_no' => 2, 'status' => 0, 'created_at' => $date, 'updated_at' => $date],
            ['row_name' => 'S', 'column_no' => 3, 'status' => 0, 'created_at' => $date, 'updated_at' => $date],
            ['row_name' => 'S', 'column_no' => 4, 'status' => 0, 'created_at' => $date, 'updated_at' => $date],
            ['row_name' => 'S', 'column_no' => 5, 'status' => 0, 'created_at' => $date, 'updated_at' => $date],
            ['row_name' => 'S', 'column_no' => 6, 'status' => 0, 'created_at' => $date, 'updated_at' => $date],
            ['row_name' => 'S', 'column_no' => 7, 'status' => 0, 'created_at' => $date, 'updated_at' => $date],
            ['row_name' => 'S', 'column_no' => 8, 'status' => 0, 'created_at' => $date, 'updated_at' => $date],
            ['row_name' => 'S', 'column_no' => 9, 'status' => 0, 'created_at' => $date, 'updated_at' => $date],
            ['row_name' => 'S', 'column_no' => 10, 'status' => 0, 'created_at' => $date, 'updated_at' => $date],
            ['row_name' => 'T', 'column_no' => 1, 'status' => 0, 'created_at' => $date, 'updated_at' => $date],
            ['row_name' => 'T', 'column_no' => 2, 'status' => 0, 'created_at' => $date, 'updated_at' => $date],
            ['row_name' => 'T', 'column_no' => 3, 'status' => 0, 'created_at' => $date, 'updated_at' => $date],
            ['row_name' => 'T', 'column_no' => 4, 'status' => 0, 'created_at' => $date, 'updated_at' => $date],
            ['row_name' => 'T', 'column_no' => 5, 'status' => 0, 'created_at' => $date, 'updated_at' => $date],
            ['row_name' => 'T', 'column_no' => 6, 'status' => 0, 'created_at' => $date, 'updated_at' => $date],
            ['row_name' => 'T', 'column_no' => 7, 'status' => 0, 'created_at' => $date, 'updated_at' => $date],
            ['row_name' => 'T', 'column_no' => 8, 'status' => 0, 'created_at' => $date, 'updated_at' => $date],
            ['row_name' => 'T', 'column_no' => 9, 'status' => 0, 'created_at' => $date, 'updated_at' => $date],
            ['row_name' => 'T', 'column_no' => 10, 'status' => 0, 'created_at' => $date, 'updated_at' => $date],
        ];
        DB::table('seats')->insert($seats);
    }
}
